 export const routeTitles = {
    "/admin": "Panel de Administración",
    "/admin/ListadoNormativa": "Listado de Normativas",
    "/admin/NuevaNormativa": "Nueva Normativa",
    "/admin/ListadoNormativa?filter=deleted": "Normativas Eliminadas",
    "/admin/ListadoNormativa?filter=unpublish": "Normativas Despublicadas",
    "/admin/NuevoUsuario": "Crear Usuario",
    "/admin/ListadoUsuarios": "Usuarios",
    "/admin/NuevaDependencia": "Nueva Dependencia",
    "/admin/ListadoDependencias": "Dependencias",
    "/admin/NuevoEmisor": "Nuevo Emisor",
    "/admin/ListadoEmisores": "Emisores",
    "/admin/AuditoriaUsuariosIngresosEgresos": "Auditoría Ingresos y Egresos",
    "/admin/AuditoriaUsuariosVisitas": "Auditoría Visitas",
    "/admin/AuditoriaNormativas": "Auditoría de Normativas",
    "/admin/NuevaPalabraClave": "Nueva Palabra Clave",
    "/admin/ListadoPalabrasClave": "Palabras Clave",
    "/admin/perfil": "Perfil de Usuario",
  }; 